language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_install:
  - npm install codecov.io coveralls request
script:
  - npm install
  - npm run test:coverage

after_success:
  - npm run coverage:combine
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
